# Generated by Django 6.0.7 on 2026-07-09 10:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Capture",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("device", models.CharField(db_index=True, max_length=50)),
                ("app", models.CharField(blank=True, default="", max_length=255)),
                ("window", models.CharField(blank=True, default="", max_length=500)),
                ("url", models.URLField(blank=True, default="", max_length=2000)),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="captures/%Y-%m-%d/"),
                ),
                ("has_image", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="captures_ca_device_3537c7_idx",
                    ),
                    models.Index(
                        fields=["app", "timestamp"], name="captures_ca_app_ec5e60_idx"
                    ),
                ],
            },
        ),
    ]
