# Generated by Django 5.2.15 on 2026-07-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captures", "0002_activitysummary_project_capture_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitysummary",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("waiting", "Waiting")],
                default="active",
                max_length=10,
            ),
        ),
    ]
